
http://localhost:8080/v1/auth/dummy-unauthorized

###

http://localhost:8080/v1/auth/dummy-authorized

###
POST http://localhost:8080/v1/auth/user/registration
Content-Type: application/json

{ "username": "yogesh", "password": "yogesh_dada" }