
http://localhost:8080/v1/auth/dummy-unauthorized

### Authorization using JWT token returned by authentication endpoints

http://localhost:8080/v1/auth/dummy-authorized
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5b2dlc2giLCJpYXQiOjE2NzUwOTk0MDksImV4cCI6MTY3NTA5OTQzOX0.AxvBsry6SSszA2WwQIndVzUCse2Rw8aG6lq5S1dso_Q

###
POST http://localhost:8080/v1/auth/user/registration
Content-Type: application/json

{ "username": "yogesh", "password": "yogesh_dada" }




### valid password authentication
POST http://localhost:8080/v1/auth/user/authentication
Content-Type: application/json

{ "username": "yogesh", "password": "yogesh_dada" }

### invalid password authentication
POST http://localhost:8080/v1/auth/user/authentication
Content-Type: application/json

{ "username": "yogesh", "password": "wrong_password" }

### invalid username authentication
POST http://localhost:8080/v1/auth/user/authentication
Content-Type: application/json

{ "username": "aditya", "password": "yogesh_dada" }




### valid password authentication - AUTH_MANAGER
POST http://localhost:8080/v1/auth/user/spring-authentication
Content-Type: application/json

{ "username": "yogesh", "password": "yogesh_dada" }

### invalid password authentication - AUTH_MANAGER
POST http://localhost:8080/v1/auth/user/spring-authentication
Content-Type: application/json

{ "username": "yogesh", "password": "wrong_password" }

### invalid username authentication - AUTH_MANAGER
POST http://localhost:8080/v1/auth/user/spring-authentication
Content-Type: application/json

{ "username": "aditya", "password": "yogesh_dada" }